// VIVID IELTS — Grammar Hub content: all 12 tenses.
// Each tense: structure, usage rules, signal words, common mistakes,
// practice exercises (fill-in-the-blank), and a 15-question test.
// Pass mark for the test is 70% (11/15) — enforced in grammar-lesson.js.

const GRAMMAR_TENSES = [

// ==================================================================
{
  id: 1,
  name: 'Present Simple',
  subtitle: 'Habits, routines, facts, and permanent truths',
  structure: {
    pos: 'Subject + base verb (+ -s/-es for he/she/it)',
    neg: "Subject + don't/doesn't + base verb",
    q: 'Do/Does + subject + base verb?'
  },
  usage: [
    { title: 'Habits and routines', explain: 'Actions that happen regularly or repeatedly.', example: 'She drinks coffee every morning.' },
    { title: 'General truths and facts', explain: 'Things that are always true, including scientific facts.', example: 'Water boils at 100°C.' },
    { title: 'Permanent situations', explain: 'Long-lasting states, jobs, or characteristics.', example: 'He works as an engineer in Tashkent.' },
    { title: 'Scheduled events', explain: 'Timetables, programmes, and fixed schedules (even in the future).', example: 'The train leaves at 9 pm tonight.' },
  ],
  signalWords: ['always', 'usually', 'often', 'sometimes', 'rarely', 'never', 'every day', 'on Mondays', 'once a week'],
  mistakes: [
    { wrong: 'She go to school.', right: 'She goes to school.', note: "Add -s/-es to the verb for he/she/it (third person singular)." },
    { wrong: "He don't like tea.", right: "He doesn't like tea.", note: "Use doesn't (not don't) with he/she/it." },
    { wrong: 'Does she likes coffee?', right: 'Does she like coffee?', note: 'After do/does, use the base verb — no extra -s.' },
  ],
  exercises: [
    { prompt: 'My sister ___ (work) at a hospital.', answer: 'works' },
    { prompt: 'They ___ (not/like) horror movies.', answer: "don't like" },
    { prompt: '___ you ___ (speak) French?', answer: 'Do you speak' },
    { prompt: 'The sun ___ (rise) in the east.', answer: 'rises' },
    { prompt: 'He ___ (not/eat) meat.', answer: "doesn't eat" },
    { prompt: '___ your father ___ (drive) to work?', answer: 'Does your father drive' },
    { prompt: 'We usually ___ (have) dinner at 8.', answer: 'have' },
    { prompt: 'It ___ (not/rain) much here in summer.', answer: "doesn't rain" },
  ],
  test: [
    { q: 'She ___ tennis every weekend.', options: ['play', 'plays', 'playing', 'is play'], correct: 1 },
    { q: 'They ___ in London.', options: ['lives', 'living', 'live', 'is living'], correct: 2 },
    { q: 'He ___ coffee in the morning.', options: ["don't drink", "doesn't drinks", "doesn't drink", "not drinks"], correct: 2 },
    { q: '___ she work on Saturdays?', options: ['Do', 'Does', 'Is', 'Are'], correct: 1 },
    { q: 'Water ___ at 0°C.', options: ['freeze', 'freezes', 'is freezing', 'froze'], correct: 1 },
    { q: 'I ___ not understand this question.', options: ['do', 'does', 'am', 'did'], correct: 0 },
    { q: 'My brother ___ football every Friday.', options: ['play', 'plays', 'is playing', 'played'], correct: 1 },
    { q: 'The shop ___ at 9 am.', options: ['open', 'opens', 'opening', 'is open'], correct: 1 },
    { q: 'Choose the correct question:', options: ['Does you like pizza?', 'Do you likes pizza?', 'Do you like pizza?', 'Are you like pizza?'], correct: 2 },
    { q: 'We ___ TV every evening.', options: ['watch', 'watches', 'watching', 'is watch'], correct: 0 },
    { q: 'Cats ___ mice.', options: ['catch', 'catches', 'is catching', 'caught'], correct: 0 },
    { q: 'She ___ speak Russian fluently.', options: ["don't", "doesn't", 'not', 'no'], correct: 1 },
    { q: 'Which sentence uses Present Simple correctly?', options: ['He is work every day.', 'He works every day.', 'He working every day.', 'He worked every day.'], correct: 1 },
    { q: 'This tense is best used for:', options: ['An action happening right now', 'A habit or routine', 'An action finished in the past', 'A future plan already arranged'], correct: 1 },
    { q: 'My parents ___ in a small village.', options: ['lives', 'living', 'live', 'lived'], correct: 2 },
  ],
},

// ==================================================================
{
  id: 2,
  name: 'Present Continuous',
  subtitle: 'Actions happening now, and fixed future arrangements',
  structure: {
    pos: 'Subject + am/is/are + verb-ing',
    neg: 'Subject + am/is/are + not + verb-ing',
    q: 'Am/Is/Are + subject + verb-ing?'
  },
  usage: [
    { title: 'Actions happening now', explain: 'Something in progress at the moment of speaking.', example: 'She is studying for her IELTS exam right now.' },
    { title: 'Temporary situations', explain: 'Actions happening around the present time, but not permanent.', example: "I'm staying with my cousin this month." },
    { title: 'Future arrangements', explain: 'Fixed plans, usually with a time expression.', example: "We're meeting the teacher tomorrow at 10." },
    { title: 'Changing or developing situations', explain: 'Trends and gradual change.', example: 'The climate is changing rapidly.' },
  ],
  signalWords: ['now', 'right now', 'at the moment', 'currently', 'these days', 'Look!', 'Listen!'],
  mistakes: [
    { wrong: 'She is knowing the answer.', right: 'She knows the answer.', note: 'Stative verbs (know, like, want, believe) are usually not used in continuous forms.' },
    { wrong: 'He going to school now.', right: 'He is going to school now.', note: "Don't forget the auxiliary am/is/are." },
    { wrong: 'They is playing football.', right: 'They are playing football.', note: 'Use are with they/we/you, not is.' },
  ],
  exercises: [
    { prompt: 'I ___ (write) an essay right now.', answer: 'am writing' },
    { prompt: 'She ___ (not/listen) to music at the moment.', answer: 'is not listening' },
    { prompt: '___ they ___ (watch) a film tonight?', answer: 'Are they watching' },
    { prompt: 'We ___ (have) a meeting this afternoon.', answer: 'are having' },
    { prompt: 'Look! It ___ (rain) heavily.', answer: 'is raining' },
    { prompt: 'He ___ (not/work) today; he is on holiday.', answer: 'is not working' },
    { prompt: 'More people ___ (become) vegetarian these days.', answer: 'are becoming' },
    { prompt: '___ you ___ (use) this chair?', answer: 'Are you using' },
  ],
  test: [
    { q: 'She ___ a letter right now.', options: ['write', 'writes', 'is writing', 'wrote'], correct: 2 },
    { q: 'We ___ dinner at the moment.', options: ['is having', 'are having', 'have', 'having'], correct: 1 },
    { q: '___ he sleeping now?', options: ['Do', 'Does', 'Is', 'Are'], correct: 2 },
    { q: 'I ___ not understand what you mean right now.', options: ['am', 'is', 'are', 'do'], correct: 0 },
    { q: 'Choose the correct sentence.', options: ['They is studying English.', 'They studying English.', 'They are studying English.', 'They studies English.'], correct: 2 },
    { q: 'Which verb is usually NOT used in continuous form?', options: ['run', 'know', 'eat', 'write'], correct: 1 },
    { q: 'Listen! Someone ___ at the door.', options: ['knock', 'knocks', 'is knocking', 'knocked'], correct: 2 },
    { q: 'We ___ to Samarkand next weekend (already arranged).', options: ['travel', 'are travelling', 'travelled', 'travels'], correct: 1 },
    { q: 'My English ___ better every day.', options: ['get', 'gets', 'is getting', 'got'], correct: 2 },
    { q: "She isn't here — she ___ a shower.", options: ['take', 'takes', 'is taking', 'took'], correct: 2 },
    { q: 'Fill the gap: I ___ this book at the moment.', options: ['read', 'reads', 'am reading', 'have read'], correct: 2 },
    { q: 'Present Continuous is used for:', options: ['Permanent facts', 'An action in progress now', 'A finished past action', 'A habitual routine'], correct: 1 },
    { q: '___ your parents living abroad this year?', options: ['Do', 'Does', 'Are', 'Is'], correct: 2 },
    { q: "He ___ his phone; he lost it.", options: ["isn't using", "doesn't use", "not using", "don't use"], correct: 0 },
    { q: 'Choose the correct negative form.', options: ["She don't working.", "She isn't working.", "She not working.", "She doesn't working."], correct: 1 },
  ],
},

// ==================================================================
{
  id: 3,
  name: 'Present Perfect',
  subtitle: 'A link between the past and now — experiences, changes, and unfinished time',
  structure: {
    pos: 'Subject + have/has + past participle',
    neg: "Subject + haven't/hasn't + past participle",
    q: 'Have/Has + subject + past participle?'
  },
  usage: [
    { title: 'Life experiences', explain: 'Something that happened at an unspecified time in your life.', example: 'I have visited Paris three times.' },
    { title: 'Recent actions with present result', explain: "A finished action that affects the present moment.", example: "She has lost her keys (so she can't get in now)." },
    { title: 'Unfinished time periods', explain: 'Actions within a period that continues up to now.', example: 'I have read two books this month.' },
    { title: 'Actions continuing up to now', explain: 'With for/since, showing duration up to the present.', example: 'They have lived here since 2019.' },
  ],
  signalWords: ['ever', 'never', 'already', 'yet', 'just', 'so far', 'recently', 'for', 'since'],
  mistakes: [
    { wrong: 'I have seen him yesterday.', right: 'I saw him yesterday.', note: "Don't use Present Perfect with a finished time expression like 'yesterday' — use Past Simple." },
    { wrong: 'She has went to Paris.', right: 'She has gone to Paris.', note: 'Use the past participle (gone), not the past simple form (went).' },
    { wrong: 'I have live here for 5 years.', right: 'I have lived here for 5 years.', note: 'The main verb must be a past participle after have/has.' },
  ],
  exercises: [
    { prompt: 'I ___ (never/be) to Japan.', answer: 'have never been' },
    { prompt: 'She ___ already (finish) her homework.', answer: 'has already finished' },
    { prompt: '___ you ever ___ (try) sushi?', answer: 'Have you ever tried' },
    { prompt: 'We ___ (live) in this city for ten years.', answer: 'have lived' },
    { prompt: 'He ___ not (call) me yet.', answer: 'has not called' },
    { prompt: 'They ___ just (arrive) at the airport.', answer: 'have just arrived' },
    { prompt: '___ she ___ (finish) the report?', answer: 'Has she finished' },
    { prompt: 'I ___ (know) him since 2015.', answer: 'have known' },
  ],
  test: [
    { q: 'I ___ my homework already.', options: ['finish', 'finished', 'have finished', 'am finishing'], correct: 2 },
    { q: 'She ___ never ___ to Africa.', options: ['has / been', 'have / been', 'has / gone', 'did / go'], correct: 0 },
    { q: '___ you seen this film before?', options: ['Do', 'Did', 'Have', 'Are'], correct: 2 },
    { q: 'We ___ in this house since 2010.', options: ['live', 'lived', 'have lived', 'are living'], correct: 2 },
    { q: 'Choose the correct sentence.', options: ['I have saw that movie.', 'I have seen that movie.', 'I has seen that movie.', 'I have see that movie.'], correct: 1 },
    { q: 'He ___ just finished his lunch.', options: ['have', 'has', 'is', 'was'], correct: 1 },
    { q: 'Which word often signals Present Perfect?', options: ['yesterday', 'last week', 'already', 'ago'], correct: 2 },
    { q: "They haven't called us ___.", options: ['already', 'yet', 'ago', 'last night'], correct: 1 },
    { q: 'I saw him ___ (correct choice for finished past time).', options: ['yesterday', 'since Monday', 'so far', 'ever'], correct: 0 },
    { q: 'She ___ for this company for five years.', options: ['works', 'worked', 'has worked', 'is working'], correct: 2 },
    { q: 'Present Perfect connects:', options: ['Two past actions', 'The past and the present', 'Two future actions', 'A habit and a fact'], correct: 1 },
    { q: 'Have they ___ their new house yet?', options: ['sell', 'sold', 'selling', 'sells'], correct: 1 },
    { q: 'I have ___ known about this.', options: ['already', 'yesterday', 'last year', 'ago'], correct: 0 },
    { q: 'Choose the correct question.', options: ['Has you finished?', 'Have she finished?', 'Have you finished?', 'Did you have finished?'], correct: 2 },
    { q: 'My father ___ his car twice this year.', options: ['sell', 'sold', 'has sold', 'is selling'], correct: 2 },
  ],
},

// ==================================================================
{
  id: 4,
  name: 'Present Perfect Continuous',
  subtitle: 'Emphasising the duration of an action up to now',
  structure: {
    pos: 'Subject + have/has + been + verb-ing',
    neg: "Subject + haven't/hasn't + been + verb-ing",
    q: 'Have/Has + subject + been + verb-ing?'
  },
  usage: [
    { title: 'Duration up to now', explain: 'An action that started in the past and is still continuing, with focus on how long.', example: 'I have been studying English for six years.' },
    { title: 'Recently finished actions with visible results', explain: 'Explains a present situation caused by a recent activity.', example: "She's tired because she has been working all day." },
    { title: 'Repeated actions over a period', explain: 'A series of actions leading up to now.', example: 'He has been applying for jobs all month.' },
  ],
  signalWords: ['for', 'since', 'all day', 'all week', 'lately', 'recently', 'how long'],
  mistakes: [
    { wrong: 'I have been knowing her for years.', right: 'I have known her for years.', note: 'Stative verbs are not used in continuous forms — use Present Perfect Simple instead.' },
    { wrong: 'She has been study all night.', right: 'She has been studying all night.', note: 'The main verb needs -ing after have/has been.' },
    { wrong: 'How long you have been waiting?', right: 'How long have you been waiting?', note: 'Invert have and the subject to form the question.' },
  ],
  exercises: [
    { prompt: 'I ___ (wait) for you for an hour.', answer: 'have been waiting' },
    { prompt: 'She ___ (not/sleep) well lately.', answer: 'has not been sleeping' },
    { prompt: 'How long ___ they ___ (learn) English?', answer: 'have they been learning' },
    { prompt: 'We ___ (work) on this project since March.', answer: 'have been working' },
    { prompt: 'His eyes are red — he ___ (cry).', answer: 'has been crying' },
    { prompt: 'It ___ (rain) all week.', answer: 'has been raining' },
    { prompt: '___ you ___ (exercise) recently?', answer: 'Have you been exercising' },
    { prompt: 'They ___ (not/talk) to each other lately.', answer: 'have not been talking' },
  ],
  test: [
    { q: 'I ___ for two hours.', options: ['study', 'have studied', 'have been studying', 'studied'], correct: 2 },
    { q: 'She looks tired; she ___ all day.', options: ['works', 'has worked', 'has been working', 'worked'], correct: 2 },
    { q: 'How long ___ you ___ here?', options: ['have / lived', 'have / been living', 'did / live', 'do / live'], correct: 1 },
    { q: 'They ___ football since 3 pm.', options: ['play', 'played', 'have been playing', 'are playing'], correct: 2 },
    { q: 'Choose the correct sentence.', options: ['I have been know him for years.', 'I have known him for years.', 'I have been knowing him for years.', 'I know him since years.'], correct: 1 },
    { q: 'He ___ not been feeling well lately.', options: ['have', 'has', 'is', 'was'], correct: 1 },
    { q: 'Which is a typical signal word for this tense?', options: ['yesterday', 'lately', 'last year', 'ago'], correct: 1 },
    { q: 'It has been snowing ___ Monday.', options: ['for', 'since', 'during', 'at'], correct: 1 },
    { q: 'We have been ___ for a solution all week.', options: ['search', 'searched', 'searching', 'searches'], correct: 2 },
    { q: 'This tense emphasises:', options: ['A single completed action', 'The duration of an activity up to now', 'A future plan', 'A permanent fact'], correct: 1 },
    { q: 'She has ___ been crying — her eyes are red.', options: ['clear', 'clearly', 'obviously', 'obvious'], correct: 2 },
    { q: 'How long have they ___ married?', options: ['be', 'been', 'being', 'was'], correct: 1 },
    { q: 'I ___ been trying to call you all morning.', options: ['have', 'has', 'am', 'was'], correct: 0 },
    { q: 'Choose the correct question.', options: ['Has you been waiting long?', 'Have you been waiting long?', 'Do you been waiting long?', 'Are you been waiting long?'], correct: 1 },
    { q: 'My hands hurt because I ___ all day.', options: ['type', 'have typed', 'have been typing', 'typed'], correct: 2 },
  ],
},

// ==================================================================
{
  id: 5,
  name: 'Past Simple',
  subtitle: 'Completed actions at a specific time in the past',
  structure: {
    pos: 'Subject + verb-ed (or irregular past form)',
    neg: "Subject + didn't + base verb",
    q: 'Did + subject + base verb?'
  },
  usage: [
    { title: 'Finished actions with a specific past time', explain: 'A single completed event.', example: 'I visited my grandmother last weekend.' },
    { title: 'A series of past actions', explain: 'Events told in sequence, as in a story.', example: 'He woke up, had breakfast, and left for work.' },
    { title: 'Past habits (with used to as an alternative)', explain: 'Repeated actions in the past that no longer happen.', example: 'She played the piano every day when she was a child.' },
  ],
  signalWords: ['yesterday', 'last week', 'last year', 'ago', 'in 2010', 'when I was young'],
  mistakes: [
    { wrong: "I didn't went there.", right: "I didn't go there.", note: "After did/didn't, use the base verb — not the past form." },
    { wrong: 'She goed to the shop.', right: 'She went to the shop.', note: "'Go' is an irregular verb — its past form is 'went', not 'goed'." },
    { wrong: 'Did you saw him?', right: 'Did you see him?', note: 'Use the base verb after did in questions.' },
  ],
  exercises: [
    { prompt: 'I ___ (watch) a film last night.', answer: 'watched' },
    { prompt: 'She ___ (not/go) to the party.', answer: 'did not go' },
    { prompt: '___ you ___ (visit) London last year?', answer: 'Did you visit' },
    { prompt: 'We ___ (have) a great time on holiday.', answer: 'had' },
    { prompt: 'He ___ (not/finish) his homework yesterday.', answer: 'did not finish' },
    { prompt: 'They ___ (buy) a new car last month.', answer: 'bought' },
    { prompt: '___ she ___ (call) you yesterday?', answer: 'Did she call' },
    { prompt: 'I ___ (see) that film three years ago.', answer: 'saw' },
  ],
  test: [
    { q: 'I ___ to the cinema yesterday.', options: ['go', 'goes', 'went', 'have gone'], correct: 2 },
    { q: 'She ___ not attend the meeting.', options: ['did', 'does', 'do', 'was'], correct: 0 },
    { q: '___ you finish the report last night?', options: ['Do', 'Did', 'Have', 'Are'], correct: 1 },
    { q: 'They ___ a new house last year.', options: ['buy', 'buys', 'bought', 'have bought'], correct: 2 },
    { q: 'Choose the correct sentence.', options: ["He didn't went home.", "He didn't go home.", 'He not went home.', "He doesn't went home."], correct: 1 },
    { q: 'We ___ dinner at 8 pm yesterday.', options: ['have', 'has', 'had', 'having'], correct: 2 },
    { q: 'Which is a typical signal word for Past Simple?', options: ['already', 'since', 'ago', 'yet'], correct: 2 },
    { q: 'Did she ___ the letter?', options: ['sent', 'send', 'sends', 'sending'], correct: 1 },
    { q: 'I ___ born in 2001.', options: ['am', 'was', 'have been', 'be'], correct: 1 },
    { q: 'Choose the correct question.', options: ['Did you saw that?', 'Did you see that?', 'Do you saw that?', 'You did see that?'], correct: 1 },
    { q: 'He ___ his keys somewhere yesterday.', options: ['lose', 'loses', 'lost', 'has lost'], correct: 2 },
    { q: 'Past Simple is best used for:', options: ['An action still continuing', 'A completed action at a specific past time', 'A present habit', 'A future plan'], correct: 1 },
    { q: 'They ___ not know the answer.', options: ['did', 'does', 'do', 'was'], correct: 0 },
    { q: 'She ___ (be) very happy when she heard the news.', options: ['is', 'was', 'has been', 'be'], correct: 1 },
    { q: 'Choose the irregular past form of "eat".', options: ['eated', 'ate', 'eaten', 'eating'], correct: 1 },
  ],
},

// ==================================================================
{
  id: 6,
  name: 'Past Continuous',
  subtitle: 'An action in progress at a specific moment in the past',
  structure: {
    pos: 'Subject + was/were + verb-ing',
    neg: 'Subject + was/were + not + verb-ing',
    q: 'Was/Were + subject + verb-ing?'
  },
  usage: [
    { title: 'Action in progress at a specific past time', explain: 'What was happening at a particular moment.', example: 'At 8 pm, I was cooking dinner.' },
    { title: 'Interrupted action', explain: 'A longer action interrupted by a shorter one (Past Simple).', example: 'I was watching TV when the phone rang.' },
    { title: 'Two parallel past actions', explain: 'Two continuous actions happening at the same time.', example: 'While she was reading, he was cleaning the kitchen.' },
    { title: 'Setting the scene in a story', explain: 'Background description in narratives.', example: 'The sun was shining and birds were singing.' },
  ],
  signalWords: ['while', 'as', 'when', 'at that moment', 'at 8 o\'clock last night'],
  mistakes: [
    { wrong: 'I was know the answer.', right: 'I knew the answer.', note: 'Stative verbs are not usually used in continuous forms.' },
    { wrong: 'While I cooked, he arrived.', right: 'While I was cooking, he arrived.', note: 'Use Past Continuous for the longer, background action.' },
    { wrong: 'They was playing outside.', right: 'They were playing outside.', note: 'Use "were" with they/we/you, not "was".' },
  ],
  exercises: [
    { prompt: 'I ___ (sleep) when you called.', answer: 'was sleeping' },
    { prompt: 'She ___ (not/listen) when the teacher explained it.', answer: 'was not listening' },
    { prompt: '___ they ___ (wait) for the bus at 9?', answer: 'Were they waiting' },
    { prompt: 'We ___ (walk) home when it started to rain.', answer: 'were walking' },
    { prompt: 'He ___ (drive) too fast when the accident happened.', answer: 'was driving' },
    { prompt: 'What ___ you ___ (do) at 10 pm last night?', answer: 'were you doing' },
    { prompt: 'While I ___ (cook), my sister ___ (study).', answer: 'was cooking / was studying' },
    { prompt: 'They ___ (not/work) when the manager arrived.', answer: 'were not working' },
  ],
  test: [
    { q: 'I ___ TV when the lights went out.', options: ['watch', 'watched', 'was watching', 'have watched'], correct: 2 },
    { q: 'They ___ football at 5 pm yesterday.', options: ['play', 'played', 'were playing', 'have played'], correct: 2 },
    { q: '___ you sleeping when I called?', options: ['Did', 'Was', 'Were', 'Are'], correct: 2 },
    { q: 'While she ___ dinner, he set the table.', options: ['cooks', 'cooked', 'was cooking', 'has cooked'], correct: 2 },
    { q: 'Choose the correct sentence.', options: ['He was working all week (finished habit).', 'He was working when I arrived.', 'He working when I arrived.', 'He was work when I arrived.'], correct: 1 },
    { q: 'We ___ not paying attention during the lecture.', options: ['was', 'were', 'did', 'have'], correct: 1 },
    { q: 'Which word often introduces Past Continuous background action?', options: ['yesterday', 'while', 'ago', 'yet'], correct: 1 },
    { q: 'The children ___ in the garden when it began to rain.', options: ['play', 'played', 'were playing', 'have played'], correct: 2 },
    { q: 'This tense usually describes:', options: ['A single finished action', 'An action in progress at a past moment', 'A present habit', 'A future arrangement'], correct: 1 },
    { q: 'I ___ a book when the power went out.', options: ['read', 'was reading', 'have read', 'reads'], correct: 1 },
    { q: 'Choose the correct question.', options: ['Was they talking?', 'Were they talking?', 'Did they talking?', 'Are they talking?'], correct: 1 },
    { q: "She wasn't ___ when I saw her.", options: ['study', 'studied', 'studying', 'studies'], correct: 2 },
    { q: 'At midnight, we ___ still working.', options: ['was', 'were', 'are', 'have been'], correct: 1 },
    { q: 'He broke his leg while he ___ skiing.', options: ['is', 'was', 'were', 'has been'], correct: 1 },
    { q: 'What ___ doing at 7 am this morning?', options: ['did you', 'were you', 'do you', 'have you'], correct: 1 },
  ],
},

// ==================================================================
{
  id: 7,
  name: 'Past Perfect',
  subtitle: 'An action completed before another point in the past',
  structure: {
    pos: 'Subject + had + past participle',
    neg: "Subject + hadn't + past participle",
    q: 'Had + subject + past participle?'
  },
  usage: [
    { title: 'Earlier of two past actions', explain: 'Shows which past action happened first.', example: 'When I arrived, the film had already started.' },
    { title: 'Cause of a later past situation', explain: 'Explains why something happened in the past.', example: 'She was tired because she had worked all night.' },
    { title: 'Reported speech (past of Present Perfect)', explain: 'Used when reporting what someone said.', example: 'He said he had finished the project.' },
  ],
  signalWords: ['already', 'just', 'never', 'by the time', 'before', 'after', 'when'],
  mistakes: [
    { wrong: 'When I arrived, he left.', right: 'When I arrived, he had left.', note: 'Use Past Perfect to show the action that happened first.' },
    { wrong: 'She had went home.', right: 'She had gone home.', note: 'Use the past participle after had, not the past simple form.' },
    { wrong: 'I had saw him before.', right: 'I had seen him before.', note: 'Use "seen" (past participle), not "saw" (past simple).' },
  ],
  exercises: [
    { prompt: 'By the time we arrived, the meeting ___ (start).', answer: 'had started' },
    { prompt: 'She ___ (not/finish) her homework before dinner.', answer: 'had not finished' },
    { prompt: '___ they ___ (leave) before you got there?', answer: 'Had they left' },
    { prompt: 'He was upset because he ___ (lose) his wallet.', answer: 'had lost' },
    { prompt: 'I ___ never (see) snow before I moved to Russia.', answer: 'had never seen' },
    { prompt: 'We ___ (already/eat) when they invited us to dinner.', answer: 'had already eaten' },
    { prompt: 'The train ___ (leave) before we reached the station.', answer: 'had left' },
    { prompt: '___ you ___ (finish) the exam when the bell rang?', answer: 'Had you finished' },
  ],
  test: [
    { q: 'By 6 pm, she ___ all her work.', options: ['finishes', 'finished', 'had finished', 'has finished'], correct: 2 },
    { q: 'When I got home, my brother ___ already ___.', options: ['has / left', 'had / left', 'was / leaving', 'did / leave'], correct: 1 },
    { q: '___ you eaten before the film started?', options: ['Did', 'Have', 'Had', 'Were'], correct: 2 },
    { q: 'She was sad because she ___ her exam.', options: ['fails', 'failed', 'had failed', 'has failed'], correct: 2 },
    { q: 'Choose the correct sentence.', options: ['He had went to bed.', 'He had gone to bed.', 'He has went to bed.', 'He had go to bed.'], correct: 1 },
    { q: 'We ___ never seen the ocean before that trip.', options: ['have', 'has', 'had', 'did'], correct: 2 },
    { q: 'Past Perfect describes:', options: ['A future plan', 'An action before another past action', 'A present habit', 'An action still happening'], correct: 1 },
    { q: 'By the time the police arrived, the thief ___ escaped.', options: ['has', 'had', 'have', 'was'], correct: 1 },
    { q: 'I realised I ___ my keys at home.', options: ['leave', 'left', 'had left', 'have left'], correct: 2 },
    { q: 'Choose the correct question.', options: ['Had she arrived when you called?', 'Has she arrived when you called?', 'Did she had arrived?', 'She had arrived when you called?'], correct: 0 },
    { q: 'They ___ not met before that party.', options: ['did', 'have', 'had', 'was'], correct: 2 },
    { q: 'After he ___ dinner, he went for a walk.', options: ['finishes', 'finished', 'had finished', 'has finished'], correct: 2 },
    { q: 'This tense is often used with:', options: ['tomorrow', 'by the time', 'right now', 'these days'], correct: 1 },
    { q: 'She told me she ___ never ___ sushi before.', options: ['has / tried', 'had / tried', 'did / try', 'was / trying'], correct: 1 },
    { q: 'The house was empty; everyone ___ already left.', options: ['has', 'had', 'have', 'did'], correct: 1 },
  ],
},

// ==================================================================
{
  id: 8,
  name: 'Past Perfect Continuous',
  subtitle: 'Emphasising the duration of an action before another past moment',
  structure: {
    pos: 'Subject + had + been + verb-ing',
    neg: "Subject + hadn't + been + verb-ing",
    q: 'Had + subject + been + verb-ing?'
  },
  usage: [
    { title: 'Duration before another past action', explain: 'How long something had been happening before a past moment.', example: 'She had been studying for three hours before the exam started.' },
    { title: 'Cause of a past situation, with emphasis on duration', explain: 'Explains a past state resulting from ongoing activity.', example: 'His eyes were red because he had been crying.' },
  ],
  signalWords: ['for', 'since', 'before', 'by the time', 'how long'],
  mistakes: [
    { wrong: 'I had been knowing him for years.', right: 'I had known him for years.', note: 'Stative verbs are not used in continuous forms.' },
    { wrong: 'She had been study when I called.', right: 'She had been studying when I called.', note: 'Add -ing to the main verb.' },
    { wrong: 'How long you had been waiting?', right: 'How long had you been waiting?', note: 'Invert had and the subject to form the question.' },
  ],
  exercises: [
    { prompt: 'By the time help arrived, they ___ (wait) for an hour.', answer: 'had been waiting' },
    { prompt: 'She ___ (not/sleep) well before the trip.', answer: 'had not been sleeping' },
    { prompt: 'How long ___ he ___ (work) there before he quit?', answer: 'had he been working' },
    { prompt: 'We ___ (travel) for six hours before we finally stopped.', answer: 'had been travelling' },
    { prompt: 'Her hands were dirty because she ___ (garden).', answer: 'had been gardening' },
    { prompt: 'It ___ (rain) all day before the storm hit.', answer: 'had been raining' },
    { prompt: '___ you ___ (learn) English long before you moved abroad?', answer: 'Had you been learning' },
    { prompt: 'They ___ (not/speak) for years before they reconciled.', answer: 'had not been speaking' },
  ],
  test: [
    { q: 'By 9 pm, we ___ for three hours.', options: ['study', 'studied', 'had been studying', 'have studied'], correct: 2 },
    { q: 'He was exhausted because he ___ all day.', options: ['works', 'worked', 'had been working', 'has worked'], correct: 2 },
    { q: 'How long ___ they ___ before the accident?', options: ['had / been driving', 'have / been driving', 'did / drive', 'do / drive'], correct: 0 },
    { q: 'She ___ not been feeling well before she saw the doctor.', options: ['has', 'had', 'was', 'did'], correct: 1 },
    { q: 'Choose the correct sentence.', options: ['I had been know her for years.', 'I had known her for years.', 'I had been knowing her for years.', 'I have been knowing her for years.'], correct: 1 },
    { q: 'This tense emphasises:', options: ['A single past event', 'Duration before another past moment', 'A present routine', 'A future plan'], correct: 1 },
    { q: 'The ground was wet because it ___ raining.', options: ['is', 'was', 'had been', 'has been'], correct: 2 },
    { q: 'They ___ been arguing for hours before they made up.', options: ['have', 'has', 'had', 'was'], correct: 2 },
    { q: 'How long had you ___ for the bus when it finally came?', options: ['wait', 'waited', 'waiting', 'waits'], correct: 2 },
    { q: 'Choose the correct question.', options: ['Had she been crying?', 'Has she been crying (about past)?', 'Did she been crying?', 'She had been crying?'], correct: 0 },
    { q: 'By the time I woke up, the sun ___ been shining for hours.', options: ['has', 'had', 'have', 'was'], correct: 1 },
    { q: 'We ___ been living there for a decade before we moved.', options: ['have', 'has', 'had', 'did'], correct: 2 },
    { q: 'His clothes were covered in paint; he ___ (paint).', options: ['had been painting', 'has painted', 'painted', 'paints'], correct: 0 },
    { q: 'This tense is most similar in meaning to:', options: ['Past Simple', 'Present Perfect Continuous, but shifted to the past', 'Future Perfect', 'Present Simple'], correct: 1 },
    { q: 'She was fluent because she ___ studying French since childhood.', options: ['is', 'was', 'had been', 'has been'], correct: 2 },
  ],
},

// ==================================================================
{
  id: 9,
  name: 'Future Simple',
  subtitle: 'Predictions, spontaneous decisions, and promises about the future',
  structure: {
    pos: 'Subject + will + base verb',
    neg: "Subject + won't + base verb",
    q: 'Will + subject + base verb?'
  },
  usage: [
    { title: 'Predictions without strong evidence', explain: 'What you think will happen.', example: 'I think it will rain tomorrow.' },
    { title: 'Spontaneous decisions', explain: 'Decisions made at the moment of speaking.', example: "It's cold — I'll close the window." },
    { title: 'Promises, offers, and requests', explain: 'Willingness to do something.', example: "I'll help you with your homework." },
    { title: 'Facts about the future', explain: 'Certain future events.', example: 'She will turn 18 next month.' },
  ],
  signalWords: ['tomorrow', 'next week', 'next year', 'soon', 'I think', 'probably', "I'm sure"],
  mistakes: [
    { wrong: 'I will to go there.', right: 'I will go there.', note: 'Do not use "to" after will — use the base verb directly.' },
    { wrong: 'She wills come tomorrow.', right: 'She will come tomorrow.', note: '"Will" never changes form, even with he/she/it.' },
    { wrong: 'Will you to help me?', right: 'Will you help me?', note: 'No "to" after will in questions either.' },
  ],
  exercises: [
    { prompt: 'I think it ___ (rain) later.', answer: 'will rain' },
    { prompt: 'She ___ (not/be) at the party tonight.', answer: 'will not be' },
    { prompt: '___ you ___ (help) me move house?', answer: 'Will you help' },
    { prompt: "I'm sure they ___ (win) the match.", answer: 'will win' },
    { prompt: "He ___ (not/pass) the exam if he doesn't study.", answer: 'will not pass' },
    { prompt: 'The phone is ringing — I ___ (answer) it.', answer: 'will answer' },
    { prompt: '___ she ___ (arrive) before noon?', answer: 'Will she arrive' },
    { prompt: 'We ___ (probably/be) late.', answer: 'will probably be' },
  ],
  test: [
    { q: 'I think she ___ the exam.', options: ['pass', 'passes', 'will pass', 'passed'], correct: 2 },
    { q: "It's heavy — I ___ carry it for you.", options: ["'ll", 'am', 'do', 'was'], correct: 0 },
    { q: '___ you call me later?', options: ['Do', 'Will', 'Are', 'Did'], correct: 1 },
    { q: 'She ___ not be at work tomorrow.', options: ['will', 'is', 'does', 'was'], correct: 0 },
    { q: 'Choose the correct sentence.', options: ['I will to visit you.', 'I will visit you.', 'I will visiting you.', 'I wills visit you.'], correct: 1 },
    { q: 'This tense is often used for:', options: ['A fixed schedule', 'A spontaneous decision', 'A past habit', 'An action in progress now'], correct: 1 },
    { q: 'The doorbell is ringing — I ___ get it.', options: ["'ll", 'am', 'was', 'do'], correct: 0 },
    { q: 'I promise I ___ never lie to you.', options: ['will', 'am', 'do', 'was'], correct: 0 },
    { q: 'Choose the correct question.', options: ['Will she comes?', 'Will she come?', 'Does she will come?', 'Is she will come?'], correct: 1 },
    { q: 'He probably ___ be late again.', options: ['will', 'is', 'does', 'was'], correct: 0 },
    { q: 'They ___ arrive around 6 pm, I think.', options: ['will', 'are', 'do', 'were'], correct: 0 },
    { q: '___ you help me carry these bags?', options: ['Do', 'Will', 'Are', 'Did'], correct: 1 },
    { q: "I'm sure everything ___ be fine.", options: ['will', 'is', 'does', 'was'], correct: 0 },
    { q: "She won't ___ time to finish today.", options: ['have', 'has', 'having', 'had'], correct: 0 },
    { q: 'Choose the negative form of "will".', options: ["don't will", "won't", "willn't", "will not to"], correct: 1 },
  ],
},

// ==================================================================
{
  id: 10,
  name: 'Future Continuous',
  subtitle: 'An action that will be in progress at a specific future time',
  structure: {
    pos: 'Subject + will be + verb-ing',
    neg: "Subject + won't be + verb-ing",
    q: 'Will + subject + be + verb-ing?'
  },
  usage: [
    { title: 'Action in progress at a future moment', explain: 'What will be happening at a specific future time.', example: 'This time tomorrow, I will be flying to London.' },
    { title: 'Polite questions about plans', explain: "Asking about someone's existing arrangements.", example: 'Will you be using the car this evening?' },
    { title: 'Future events expected as a matter of routine', explain: 'Predictable future situations.', example: 'The train will be arriving shortly.' },
  ],
  signalWords: ['this time tomorrow', 'at this time next week', 'at 8 pm tomorrow'],
  mistakes: [
    { wrong: 'I will be know the answer tomorrow.', right: 'I will know the answer tomorrow.', note: 'Stative verbs are not usually used in continuous forms — use Future Simple.' },
    { wrong: 'She will being working then.', right: 'She will be working then.', note: 'The structure is will + be + verb-ing, not will + being.' },
    { wrong: 'Will you working tomorrow?', right: 'Will you be working tomorrow?', note: 'Don\'t forget "be" between will and the -ing verb.' },
  ],
  exercises: [
    { prompt: 'This time tomorrow, I ___ (fly) to Dubai.', answer: 'will be flying' },
    { prompt: 'She ___ (not/work) at 9 pm tonight.', answer: 'will not be working' },
    { prompt: '___ you ___ (use) the kitchen at 6?', answer: 'Will you be using' },
    { prompt: 'At this time next week, we ___ (relax) on a beach.', answer: 'will be relaxing' },
    { prompt: 'He ___ (not/sleep) when we arrive.', answer: 'will not be sleeping' },
    { prompt: 'They ___ (travel) through Europe this time next month.', answer: 'will be travelling' },
    { prompt: '___ she ___ (wait) for us at the airport?', answer: 'Will she be waiting' },
    { prompt: 'I ___ (still/study) at midnight.', answer: 'will still be studying' },
  ],
  test: [
    { q: 'This time tomorrow, I ___ on a plane.', options: ['am', 'will be', 'was', 'have been'], correct: 1 },
    { q: 'She ___ working when you arrive.', options: ['will', 'will be', 'is', 'was'], correct: 1 },
    { q: '___ you be waiting at the station?', options: ['Do', 'Will', 'Are', 'Did'], correct: 1 },
    { q: 'At 8 pm, we ___ having dinner.', options: ['will', 'will be', 'are', 'were'], correct: 1 },
    { q: 'Choose the correct sentence.', options: ['I will be knowing the truth soon.', 'I will know the truth soon.', 'I be will know the truth soon.', 'I will being know the truth soon.'], correct: 1 },
    { q: 'This tense describes:', options: ['An action in progress at a future moment', 'A finished past action', 'A present habit', 'A past continuous action'], correct: 0 },
    { q: 'He ___ be sleeping when we get there.', options: ['will', 'is', 'was', 'has'], correct: 0 },
    { q: 'Will they ___ using the car tonight?', options: ['be', 'being', 'been', ''], correct: 0 },
    { q: 'Choose the correct question.', options: ['Will you working tomorrow?', 'Will you be working tomorrow?', 'Are you will working tomorrow?', 'Do you will work tomorrow?'], correct: 1 },
    { q: 'This time next year, she ___ studying abroad.', options: ['will', 'will be', 'is', 'was'], correct: 1 },
    { q: 'We ___ not be attending the ceremony.', options: ['will', 'are', 'do', 'was'], correct: 0 },
    { q: 'At noon tomorrow, I ___ (present) my project.', options: ['will present', 'will be presenting', 'present', 'am presenting'], correct: 1 },
    { q: 'They will be ___ around this time next week.', options: ['travel', 'travelling', 'travelled', 'travels'], correct: 1 },
    { q: 'Future Continuous is often used with:', options: ['yesterday', 'this time tomorrow', 'ago', 'already'], correct: 1 },
    { q: 'Choose the correct negative form.', options: ["won't be doing", "not will be doing", "will not doing", "willn't be doing"], correct: 0 },
  ],
},

// ==================================================================
{
  id: 11,
  name: 'Future Perfect',
  subtitle: 'An action that will be completed before a specific future time',
  structure: {
    pos: 'Subject + will have + past participle',
    neg: "Subject + won't have + past participle",
    q: 'Will + subject + have + past participle?'
  },
  usage: [
    { title: 'Completion before a future deadline', explain: 'An action finished before a stated future point.', example: 'By next year, I will have graduated.' },
    { title: 'Duration up to a future point (with for)', explain: 'How long something will have continued by then.', example: 'By June, we will have lived here for five years.' },
  ],
  signalWords: ['by then', 'by next year', 'by the time', 'by 2030'],
  mistakes: [
    { wrong: 'By next year, I will finished my degree.', right: 'By next year, I will have finished my degree.', note: 'Add "have" — the structure is will + have + past participle.' },
    { wrong: 'She will has left by then.', right: 'She will have left by then.', note: '"Will" never changes to "has" — always use "have" after will.' },
    { wrong: 'By 8, they will have arrive.', right: 'By 8, they will have arrived.', note: 'Use the past participle (arrived), not the base form.' },
  ],
  exercises: [
    { prompt: 'By 2030, scientists ___ (find) a cure.', answer: 'will have found' },
    { prompt: 'She ___ (not/finish) the report by Friday.', answer: 'will not have finished' },
    { prompt: '___ you ___ (complete) the course by June?', answer: 'Will you have completed' },
    { prompt: 'By the time you arrive, we ___ (leave).', answer: 'will have left' },
    { prompt: 'He ___ (not/pay) the bill by tomorrow.', answer: 'will not have paid' },
    { prompt: 'By next month, they ___ (be) married for ten years.', answer: 'will have been' },
    { prompt: '___ she ___ (graduate) by next summer?', answer: 'Will she have graduated' },
    { prompt: 'By the end of the year, I ___ (save) enough money.', answer: 'will have saved' },
  ],
  test: [
    { q: 'By next year, I ___ my degree.', options: ['finish', 'will finish', 'will have finished', 'finished'], correct: 2 },
    { q: 'By 8 pm, they ___ dinner.', options: ['will have', 'will has', 'will have had', 'have had'], correct: 2 },
    { q: '___ you have completed the project by Friday?', options: ['Do', 'Will', 'Are', 'Did'], correct: 1 },
    { q: 'She ___ not have arrived by the time we get there.', options: ['will', 'is', 'does', 'was'], correct: 0 },
    { q: 'Choose the correct sentence.', options: ['I will have finish it by Monday.', 'I will have finished it by Monday.', 'I have will finished it by Monday.', 'I will finished it by Monday.'], correct: 1 },
    { q: 'This tense describes:', options: ['A completed action before a future point', 'A present habit', 'An action in progress now', 'A past continuous action'], correct: 0 },
    { q: 'By 2025, he ___ (live) here for 20 years.', options: ['will have lived', 'will live', 'has lived', 'lived'], correct: 0 },
    { q: 'Will they ___ built the bridge by then?', options: ['have', 'has', 'had', 'be'], correct: 0 },
    { q: 'Choose the correct question.', options: ['Will she has finished?', 'Will she have finished?', 'Has she will finish?', 'Does she will finish?'], correct: 1 },
    { q: 'By the time you read this, I ___ left.', options: ['will have', 'will has', 'have', 'has'], correct: 0 },
    { q: 'We ___ not have eaten by 7.', options: ['will', 'are', 'do', 'were'], correct: 0 },
    { q: 'By next week, she ___ the exam results.', options: ['will receive', 'will have received', 'receives', 'received'], correct: 1 },
    { q: 'Future Perfect is commonly used with:', options: ['yesterday', 'by the time', 'right now', 'these days'], correct: 1 },
    { q: 'By midnight, the guests ___ (leave).', options: ['will have', 'will has', 'have', 'has'], correct: 0 },
    { q: 'Choose the correct negative form.', options: ["won't have finished", "not will have finished", "will not finished", "haven't will finish"], correct: 0 },
  ],
},

// ==================================================================
{
  id: 12,
  name: 'Future Perfect Continuous',
  subtitle: 'Emphasising the duration of an action up to a specific future point',
  structure: {
    pos: 'Subject + will have been + verb-ing',
    neg: "Subject + won't have been + verb-ing",
    q: 'Will + subject + have been + verb-ing?'
  },
  usage: [
    { title: 'Duration up to a future point', explain: 'How long an action will have continued by a certain future time.', example: 'By December, I will have been working here for ten years.' },
    { title: 'Explaining a future situation caused by ongoing activity', explain: 'Emphasises the process leading up to a future result.', example: 'She will be tired because she will have been travelling all day.' },
  ],
  signalWords: ['by then', 'by the time', 'for (+ duration)', 'by next year'],
  mistakes: [
    { wrong: 'By June, I will have been know her for ten years.', right: 'By June, I will have known her for ten years.', note: 'Stative verbs use Future Perfect Simple, not the continuous form.' },
    { wrong: 'She will have being working all day.', right: 'She will have been working all day.', note: 'The correct structure is will + have + been + verb-ing.' },
    { wrong: 'By 9, they will has been travelling for hours.', right: 'By 9, they will have been travelling for hours.', note: '"Will" is always followed by "have", never "has".' },
  ],
  exercises: [
    { prompt: 'By next month, I ___ (work) here for a year.', answer: 'will have been working' },
    { prompt: 'She ___ (not/study) for long enough by the exam date.', answer: 'will not have been studying' },
    { prompt: 'By 6 pm, we ___ (travel) for twelve hours.', answer: 'will have been travelling' },
    { prompt: '___ they ___ (build) the house for a year by December?', answer: 'Will they have been building' },
    { prompt: 'He ___ (run) for two hours by the time he finishes the marathon.', answer: 'will have been running' },
    { prompt: 'By the time you arrive, I ___ (wait) for an hour.', answer: 'will have been waiting' },
    { prompt: 'By 2026, she ___ (teach) for 15 years.', answer: 'will have been teaching' },
    { prompt: 'We ___ (not/live) here long enough by then to know the area well.', answer: 'will not have been living' },
  ],
  test: [
    { q: 'By December, I ___ here for five years.', options: ['will work', 'will have worked', 'will have been working', 'worked'], correct: 2 },
    { q: 'By 9 pm, they ___ for six hours.', options: ['will drive', 'will have driven', 'will have been driving', 'drove'], correct: 2 },
    { q: 'How long ___ you ___ by the time you finish?', options: ['will / have been studying', 'will / study', 'have / studied', 'did / study'], correct: 0 },
    { q: 'She will have been ___ all day when we arrive.', options: ['cook', 'cooked', 'cooking', 'cooks'], correct: 2 },
    { q: 'Choose the correct sentence.', options: ['I will have been know her for years.', 'I will have known her for years.', 'I will have been knowing her for years.', 'I have been knowing her for years.'], correct: 1 },
    { q: 'This tense emphasises:', options: ['A single future action', 'Duration of an action up to a future point', 'A present routine', 'A finished past action'], correct: 1 },
    { q: 'By the time he retires, he ___ teaching for 30 years.', options: ['will have', 'will have been', 'has been', 'was'], correct: 1 },
    { q: 'They will have been ___ since morning.', options: ['travel', 'travelled', 'travelling', 'travels'], correct: 2 },
    { q: 'Choose the correct question.', options: ['Will you have been waiting long?', 'Will you have waiting long?', 'Have you will been waiting long?', 'Do you will have been waiting?'], correct: 0 },
    { q: 'By 2030, scientists ___ researching this for decades.', options: ['will be', 'will have been', 'have been', 'were'], correct: 1 },
    { q: 'We ___ not have been living here long by then.', options: ['will', 'are', 'do', 'were'], correct: 0 },
    { q: 'By next year, she will have been ___ the violin for ten years.', options: ['play', 'played', 'playing', 'plays'], correct: 2 },
    { q: 'This structure is: will + have + been + ___.', options: ['base verb', 'past participle', 'verb-ing', 'past simple'], correct: 2 },
    { q: 'By midday, he will have been ___ for six hours straight.', options: ['work', 'worked', 'working', 'works'], correct: 2 },
    { q: 'Choose the correct negative form.', options: ["won't have been working", "will not been working", "haven't will be working", "won't have work"], correct: 0 },
  ],
},

];